apiVersion: v1
kind: Secret
metadata:
  name: app-credentials
  namespace: wordpress-web-app
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "d2ViYXBwQDEyMw=="
  MYSQL_DATABASE: "d29yZHByZXNzX2Ri"
  MYSQL_USER: "d3BfdXNlcg=="                                     
  MYSQL_PASSWORD: "d2ViYXBwQDEyMw=="
  WORDPRESS_DB_USER: "d3BfdXNlcg=="
  WORDPRESS_DB_PASSWORD: "d2ViYXBwQDEyMw=="
  WORDPRESS_AUTH_KEY: "d2ViYXBwd29yZHByZXNzQDEyMw=="
  WORDPRESS_SECURE_AUTH_KEY: "d2ViYXBwd29yZHByZXNzQDEyMw=="
  WORDPRESS_LOGGED_IN_KEY: "d2ViYXBwd29yZHByZXNzQDEyMw=="
  WORDPRESS_NONCE_KEY: "d2ViYXBwd29yZHByZXNzQDEyMw=="
  WORDPRESS_AUTH_SALT: "d2ViYXBwd29yZHByZXNzQDEyMw=="
  WORDPRESS_SECURE_AUTH_SALT: "d2ViYXBwd29yZHByZXNzQDEyMw=="
  WORDPRESS_LOGGED_IN_SALT: "d2ViYXBwd29yZHByZXNzQDEyMw=="
  WORDPRESS_NONCE_SALT: "d2ViYXBwd29yZHByZXNzQDEyMw=="