apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: wordpress-web-app
  labels:
    app: wordpress
    tier: frontend
    storage: ephemeral
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  selector:
    app: wordpress
    tier: frontend
    storage: ephemeral
  type: LoadBalancer